import Head from 'next/head'
import Feed from '../components/Feed';
import Sidebar from '../components/Sidebar';
import Widgets from '../components/Widgets';

export default function Home({newsResults}) {
  return (
    <div>
      <Head>
        <title>Twitter clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen mx-auto ">

      <Sidebar/>

      <Feed/>

      {/* Widgets*/}

      <Widgets newsResults={newsResults.articles}/>

      </main>
     
    </div>
  );
}


//https://saurav.tech/NewsAPI/top-headlines/category/health/in.json


export async function getServerSideProps(){
  const newsResults = await fetch ("https://saurav.tech/NewsAPI/top-headlines/category/health/in.json").then((res)=>res.json());
  return{
    props:{
      newsResults,
    },
  }
}